package com.myspace.semiannualreportsproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SemiannualReport implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("year")
	private Integer year;
	@org.kie.api.definition.type.Label("period")
	private Integer period;
	@org.kie.api.definition.type.Label("status")
	private java.lang.String status;
	@org.kie.api.definition.type.Label("description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("institution")
	private java.lang.String institution;
	@org.kie.api.definition.type.Label("assignedUser")
	private java.lang.String assignedUser;
	@org.kie.api.definition.type.Label("createdBy")
	private java.lang.String createdBy;
	@org.kie.api.definition.type.Label("createdAt")
	private java.util.Date createdAt;
	@org.kie.api.definition.type.Label("updateBy")
	private java.lang.String updateBy;
	@org.kie.api.definition.type.Label("updatedAt")
	private java.util.Date updatedAt;

	@org.kie.api.definition.type.Label("processInstanceId")
	private Long processInstanceId;

	@org.kie.api.definition.type.Label("id")
	private java.lang.String id;

	@org.kie.api.definition.type.Label(value = "documents")
	private java.util.List<com.myspace.semiannualreportsproject.Documents> documents;

	public SemiannualReport() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getInstitution() {
		return this.institution;
	}

	public void setInstitution(java.lang.String institution) {
		this.institution = institution;
	}

	public java.lang.String getAssignedUser() {
		return this.assignedUser;
	}

	public void setAssignedUser(java.lang.String assignedUser) {
		this.assignedUser = assignedUser;
	}

	public java.lang.String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(java.lang.String createdBy) {
		this.createdBy = createdBy;
	}

	public java.util.Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.util.Date createdAt) {
		this.createdAt = createdAt;
	}

	public java.lang.String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(java.lang.String updateBy) {
		this.updateBy = updateBy;
	}

	public java.util.Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.Integer getYear() {
		return this.year;
	}

	public void setYear(java.lang.Integer year) {
		this.year = year;
	}

	public java.lang.Integer getPeriod() {
		return this.period;
	}

	public void setPeriod(java.lang.Integer period) {
		this.period = period;
	}

	public java.lang.Long getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(java.lang.Long processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public java.util.List<com.myspace.semiannualreportsproject.Documents> getDocuments() {
		return this.documents;
	}

	public void setDocuments(
			java.util.List<com.myspace.semiannualreportsproject.Documents> documents) {
		this.documents = documents;
	}

	public SemiannualReport(
			java.lang.String name,
			java.lang.Integer year,
			java.lang.Integer period,
			java.lang.String status,
			java.lang.String description,
			java.lang.String institution,
			java.lang.String assignedUser,
			java.lang.String createdBy,
			java.util.Date createdAt,
			java.lang.String updateBy,
			java.util.Date updatedAt,
			java.lang.Long processInstanceId,
			java.lang.String id,
			java.util.List<com.myspace.semiannualreportsproject.Documents> documents) {
		this.name = name;
		this.year = year;
		this.period = period;
		this.status = status;
		this.description = description;
		this.institution = institution;
		this.assignedUser = assignedUser;
		this.createdBy = createdBy;
		this.createdAt = createdAt;
		this.updateBy = updateBy;
		this.updatedAt = updatedAt;
		this.processInstanceId = processInstanceId;
		this.id = id;
		this.documents = documents;
	}

}